### ISSUE TITLE
Unknown "fileIcon" function

### ISSUE THREAD

**Issue by Quovandius** [artgris/MediaBundle#11]
Hi,

Another issue sorry =)

The function fileIcon is called but unknown. I think i have missed a declaration ?
Thanx for your help.

**Comment by Arkounay** [comment]
The bundle uses [artgris/FileManagerBundle](https://github.com/artgris/FileManagerBundle) and needs it installed as prerequisite.
It'll work if you add  `Artgris\Bundle\FileManagerBundle\ArtgrisFileManagerBundle::class => ['all' => true]` in `bundles.php` (for Symfony 4, for Symfony 3 it should be something like  `new Artgris\Bundle\FileManagerBundle\ArtgrisFileManagerBundle()` in `AppKernel.php`)

Then simply you can add this config (in `config.yml` for symfony3, or in a new file `artgris_file_manager.yaml` in symfony 4)

```yaml
artgris_file_manager:
    web_dir: public
    conf:
        default:
            dir: "../public/uploads/"
            type: image 
```
