### ISSUE TITLE
how to configure path images? [question] 

### ISSUE THREAD

**Issue by Telous** [artgris/MediaBundle#23]
Im installed "FileManagerBundle" and "MediaBundle" on Symfony 4, both of them are runnig fine, but the path of images are too diferent compared to the examples.

This is the path I get on textbox when I select an image:
`/images/manager/file/tempsnip.png?module=1&conf=default&tree=0`

and the correct path, following the docs is somthing like this
`/public/uploads/tempsnip.png`

Example image:
![image](https://user-images.githubusercontent.com/24831041/46390645-2eb52500-c6af-11e8-858d-ec44628b84a1.png)

config/packages/artgris_file_manager.yaml
```
artgris_file_manager:
    web_dir: public
    conf:
        # route: public
        default:
            dir: "public/uploads"
```
config/routes.yaml

```
artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type: annotation
    prefix: /manager

artgris_media:
    resource: "@ArtgrisMediaBundle/Resources/config/routing.yml"
```

what am I doing wrong?
