### ISSUE TITLE
SF3.4 service configuration not working

### ISSUE THREAD

**Issue by johan-Rm** [artgris/MediaBundle#31]
Hi,

when i install version 4.0 of media bundle in sf3.4 i come across this error:

>  The service "filemanager_configuration" has a dependency on a non-existent   
>   service "parameter_bag".  

that I correct by passing the service_container in arguments :+1: 
```yaml
filemanager_configuration:
    class: Artgris\Bundle\MediaBundle\Service\FileManagerConfigurationService
    tags:
        - { name: twig.extension }
    arguments: ['@service_container']
```

and modifying the constructor as follows :

```php
public function __construct($container)
{
    $this->artgrisFileManagerConfig = $container->getParameterBag('artgris_file_manager');
}
```

Thanks
