### ISSUE TITLE
SF3.4 form types not working

### ISSUE THREAD

**Issue by johan-Rm** [artgris/MediaBundle#33]
Hi,

when i install version 4.0 of media bundle in sf3.4 and when I want to use this:

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        ...
        types:
            media: Artgris\Bundle\MediaBundle\Form\Type\MediaType
            media_collection: Artgris\Bundle\MediaBundle\Form\Type\MediaCollectionType
```
 i come across this error:

```php
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "requiresSQLCommentHint" 
```

I do not have the solution can someone help me?

Thanks
