### ISSUE TITLE
cropped image output path

### ISSUE THREAD

**Issue by elpince** [artgris/MediaBundle#37]
Hello, in my project I need the end user to be able to upload and crop images. Your bundles do this work just fine but I still have an issue : 

How do I change where cropped images are stored ? Any way I try to configure it, cropped images end up in a sibling directory.
example : 
```
artgris_file_manager:
    web_dir: public
    conf:
        news:
            dir: "../public/uploads/images"
            regex: '.(jpe?g)|.png$'
            accept: '.jpeg,.jpg,.png'
            upload:
                max_width: 1920
                max_height: 1080
```
so when I open the file manager in my form, I have access to the /public/uploads/images directory.

My issue is that every cropped image is saved in a new /public/uploads/imagescropped directory, cropped images will therefore always be invisible from the directory their original is from, how do I change that ?
